project_id = "tytilcbuyphlowkolpsk"

[functions.upload-media]
verify_jwt = false

[functions.delete-media]
verify_jwt = false

[functions.generate-invoices]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.tranzila-webhook]
verify_jwt = false

[functions.get-signature-info]
verify_jwt = false

[functions.submit-signature]
verify_jwt = false

[functions.check-expiring-policies]
verify_jwt = false

[functions.signature-page]
verify_jwt = false

[functions.payment-result]
verify_jwt = false

[functions.wordpress-import]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-manual-reminder]
verify_jwt = true

[functions.auth-email-start]
verify_jwt = false

[functions.auth-email-verify]
verify_jwt = false

[functions.auth-sms-start]
verify_jwt = false

[functions.auth-sms-verify]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.check-cheque-reminders]
verify_jwt = false

[functions.generate-client-report]
verify_jwt = true

[functions.generate-broker-report]
verify_jwt = true
