project_id = "tytilcbuyphlowkolpsk"

[functions.upload-media]
verify_jwt = false

[functions.delete-media]
verify_jwt = false

[functions.delete-policy]
verify_jwt = false

[functions.generate-invoices]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.tranzila-webhook]
verify_jwt = false

[functions.get-signature-info]
verify_jwt = false

[functions.submit-signature]
verify_jwt = false

[functions.check-expiring-policies]
verify_jwt = false

[functions.signature-page]
verify_jwt = false

[functions.payment-result]
verify_jwt = false

[functions.wordpress-import]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-manual-reminder]
verify_jwt = true

[functions.auth-email-start]
verify_jwt = false

[functions.auth-email-verify]
verify_jwt = false

[functions.auth-sms-start]
verify_jwt = false

[functions.auth-sms-verify]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.check-cheque-reminders]
verify_jwt = false

[functions.generate-client-report]
verify_jwt = true

[functions.generate-broker-report]
verify_jwt = true

[functions.tranzila-broker-init]
verify_jwt = true

[functions.broker-payment-result]
verify_jwt = false

[functions.tranzila-broker-status]
verify_jwt = true

[functions.send-package-invoice-sms]
verify_jwt = true

[functions.generate-renewals-report]
verify_jwt = true

[functions.send-renewal-reminders]
verify_jwt = true

[functions.cron-renewal-reminders]
verify_jwt = false

[functions.send-marketing-sms]
verify_jwt = true

[functions.cron-birthday-license-sms]
verify_jwt = false

[functions.click2call]
verify_jwt = true

[functions.generate-payment-receipt]
verify_jwt = true

[functions.generate-client-payments-invoice]
verify_jwt = true
